# Generated by Django 4.0.2 on 2022-02-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_blog', models.CharField(max_length=30)),
                ('subtitle_blog', models.CharField(max_length=30)),
                ('body', models.TextField()),
                ('author', models.CharField(max_length=30)),
                ('date', models.DateField()),
            ],
        ),
    ]
