# Generated by Django 4.0.2 on 2022-02-22 02:32

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content_resume', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('content_upload', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('publication_date', models.DateTimeField()),
                ('picture', models.ImageField(upload_to='')),
                ('author', models.CharField(max_length=30)),
            ],
        ),
    ]
