# Generated by Django 4.0.2 on 2022-02-25 02:31

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1_Blog_Coder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content_resume',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
