# Generated by Django 4.0.2 on 2022-02-20 15:20

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1_Blog_Coder', '0002_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_upload',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
